# Generated by Django 5.0.6 on 2024-07-08 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknown', models.IntegerField(default=0)),
                ('appleBad', models.IntegerField(default=0)),
                ('bananaBad', models.IntegerField(default=0)),
                ('orangeBad', models.IntegerField(default=0)),
                ('pomegranateBad', models.IntegerField(default=0)),
                ('appleGood', models.IntegerField(default=0)),
                ('bananaGood', models.IntegerField(default=0)),
                ('orangeGood', models.IntegerField(default=0)),
                ('pomegranateGood', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fruitsImages/')),
                ('imagesDetected', models.ImageField(blank=True, null=True, upload_to='fruitsDetectedImages/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('fruitsState', models.CharField(blank=True, max_length=500)),
                ('unknown', models.IntegerField(default=0)),
                ('bad_apple', models.IntegerField(default=0)),
                ('bad_banana', models.IntegerField(default=0)),
                ('bad_orange', models.IntegerField(default=0)),
                ('bad_pomegranate', models.IntegerField(default=0)),
                ('good_apple', models.IntegerField(default=0)),
                ('good_banana', models.IntegerField(default=0)),
                ('good_orange', models.IntegerField(default=0)),
                ('good_pomegranate', models.IntegerField(default=0)),
                ('fruitCount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruitsState.fruitcount')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
